{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "dc4f5779_9954ff2e",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 10
      },
      "lineNbr": 0,
      "author": {
        "id": 1000002
      },
      "writtenOn": "2022-03-31T08:12:07Z",
      "side": 1,
      "message": "LGTM too",
      "revId": "f57867264a7d661bb904df9f4404521f8e21f022",
      "serverId": "dd02978d-1a8e-36d7-bcc0-a5723e5c0abd"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "065648b6_f0ef4606",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 10
      },
      "lineNbr": 0,
      "author": {
        "id": 1000002
      },
      "writtenOn": "2022-03-31T08:12:30Z",
      "side": 1,
      "message": "And it was merged anyway, sorry for the spam.",
      "revId": "f57867264a7d661bb904df9f4404521f8e21f022",
      "serverId": "dd02978d-1a8e-36d7-bcc0-a5723e5c0abd"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "e191338e_5f5e871f",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 10
      },
      "lineNbr": 0,
      "author": {
        "id": 1001791
      },
      "writtenOn": "2022-04-12T13:49:03Z",
      "side": 1,
      "message": "This commit breaks compilation from official tarballs (i.e. https://commondatastorage.googleapis.com/chromium-browser-official/chromium-102.0.4987.0.tar.xz ) because it tries to use git to obtain the revision, but that\u0027s not available in the tarball.",
      "revId": "f57867264a7d661bb904df9f4404521f8e21f022",
      "serverId": "dd02978d-1a8e-36d7-bcc0-a5723e5c0abd"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "b95fefd9_53e9cff4",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 10
      },
      "lineNbr": 0,
      "author": {
        "id": 1000002
      },
      "writtenOn": "2022-04-12T13:52:59Z",
      "side": 1,
      "message": "Yeah :/. This should now be fixed as https://dawn-review.googlesource.com/c/dawn/+/85745 landed a while ago. Sorry for the breakage.",
      "parentUuid": "e191338e_5f5e871f",
      "revId": "f57867264a7d661bb904df9f4404521f8e21f022",
      "serverId": "dd02978d-1a8e-36d7-bcc0-a5723e5c0abd"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "9fde26ed_cd1f4cfd",
        "filename": "generator/dawn_version_generator.py",
        "patchSetId": 10
      },
      "lineNbr": 25,
      "author": {
        "id": 1000002
      },
      "writtenOn": "2022-03-31T08:12:07Z",
      "side": 1,
      "message": "[1]",
      "revId": "f57867264a7d661bb904df9f4404521f8e21f022",
      "serverId": "dd02978d-1a8e-36d7-bcc0-a5723e5c0abd"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "769cb08f_1437586e",
        "filename": "generator/dawn_version_generator.py",
        "patchSetId": 10
      },
      "lineNbr": 25,
      "author": {
        "id": 1000002
      },
      "writtenOn": "2022-03-31T08:12:17Z",
      "side": 1,
      "message": "Ack",
      "parentUuid": "9fde26ed_cd1f4cfd",
      "revId": "f57867264a7d661bb904df9f4404521f8e21f022",
      "serverId": "dd02978d-1a8e-36d7-bcc0-a5723e5c0abd"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "6e7f8bdb_6678ff3b",
        "filename": "generator/dawn_version_generator.py",
        "patchSetId": 10
      },
      "lineNbr": 26,
      "author": {
        "id": 1000076
      },
      "writtenOn": "2022-04-06T20:54:25Z",
      "side": 1,
      "message": "Would you consider switching this to use subprocess.call or subprocess.check_call? We (Skia) have bots with python \u003c 3.5 (when .run was added), so we\u0027re getting errors when running the script:\n\nhttps://logs.chromium.org/logs/skia/5a193c9a06193811/+/steps/ninja/0/stdout",
      "range": {
        "startLine": 26,
        "startChar": 13,
        "endLine": 26,
        "endChar": 27
      },
      "revId": "f57867264a7d661bb904df9f4404521f8e21f022",
      "serverId": "dd02978d-1a8e-36d7-bcc0-a5723e5c0abd"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "071547cc_68a26b2b",
        "filename": "generator/dawn_version_generator.py",
        "patchSetId": 10
      },
      "lineNbr": 26,
      "author": {
        "id": 1000076
      },
      "writtenOn": "2022-04-06T20:58:41Z",
      "side": 1,
      "message": "Actually, sorry - those bots do have newer (3.7.3) python, so I\u0027m not really sure what\u0027s broken here. It works for me locally (when trying to roll new Dawn manually), but our bots are consistently failing to run the version generator script.",
      "parentUuid": "6e7f8bdb_6678ff3b",
      "range": {
        "startLine": 26,
        "startChar": 13,
        "endLine": 26,
        "endChar": 27
      },
      "revId": "f57867264a7d661bb904df9f4404521f8e21f022",
      "serverId": "dd02978d-1a8e-36d7-bcc0-a5723e5c0abd"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "fdb1af80_230000dd",
        "filename": "generator/dawn_version_generator.py",
        "patchSetId": 10
      },
      "lineNbr": 26,
      "author": {
        "id": 1002831
      },
      "writtenOn": "2022-04-06T21:09:22Z",
      "side": 1,
      "message": "Hmm, do you have a link to a failure I could take a look at also? I could probably also switch to using subprocess.call, but would be nice to have a way to test whether it works on the bots if I do. Thanks!",
      "parentUuid": "071547cc_68a26b2b",
      "range": {
        "startLine": 26,
        "startChar": 13,
        "endLine": 26,
        "endChar": 27
      },
      "revId": "f57867264a7d661bb904df9f4404521f8e21f022",
      "serverId": "dd02978d-1a8e-36d7-bcc0-a5723e5c0abd"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "872a11d4_1cd72876",
        "filename": "generator/dawn_version_generator.py",
        "patchSetId": 10
      },
      "lineNbr": 26,
      "author": {
        "id": 1000076
      },
      "writtenOn": "2022-04-06T21:19:03Z",
      "side": 1,
      "message": "Here\u0027s the CL where I was trying to do the roll: https://skia-review.googlesource.com/c/skia/+/528118/\n\nSwarming task for the failed builder: https://chromium-swarm.appspot.com/task?id\u003d5a193c9a06193810\n\nFrom doing other research online, I think there are other possible reasons. One is that GN always invokes python using `python`, so it\u0027s possible that for the user running the task, that still resolves to python2.",
      "parentUuid": "fdb1af80_230000dd",
      "range": {
        "startLine": 26,
        "startChar": 13,
        "endLine": 26,
        "endChar": 27
      },
      "revId": "f57867264a7d661bb904df9f4404521f8e21f022",
      "serverId": "dd02978d-1a8e-36d7-bcc0-a5723e5c0abd"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "ccf2d6dd_8b18c1c6",
        "filename": "generator/dawn_version_generator.py",
        "patchSetId": 10
      },
      "lineNbr": 26,
      "author": {
        "id": 1000076
      },
      "writtenOn": "2022-04-06T21:22:25Z",
      "side": 1,
      "message": "... and I just learned about \"script_executable\", so I\u0027m going to try adding that to our top level .gn file.",
      "parentUuid": "872a11d4_1cd72876",
      "range": {
        "startLine": 26,
        "startChar": 13,
        "endLine": 26,
        "endChar": 27
      },
      "revId": "f57867264a7d661bb904df9f4404521f8e21f022",
      "serverId": "dd02978d-1a8e-36d7-bcc0-a5723e5c0abd"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "284db568_1c53fb7b",
        "filename": "generator/dawn_version_generator.py",
        "patchSetId": 10
      },
      "lineNbr": 26,
      "author": {
        "id": 1002831
      },
      "writtenOn": "2022-04-06T23:18:37Z",
      "side": 1,
      "message": "Ok, sorry for delayed response. Were you able to get it to work? I notice that our .gn file also has an override for that, so I\u0027m surprised that it\u0027s not being picked up.",
      "parentUuid": "ccf2d6dd_8b18c1c6",
      "range": {
        "startLine": 26,
        "startChar": 13,
        "endLine": 26,
        "endChar": 27
      },
      "revId": "f57867264a7d661bb904df9f4404521f8e21f022",
      "serverId": "dd02978d-1a8e-36d7-bcc0-a5723e5c0abd"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "5c1d9220_927c7bab",
        "filename": "generator/dawn_version_generator.py",
        "patchSetId": 10
      },
      "lineNbr": 26,
      "author": {
        "id": 1000076
      },
      "writtenOn": "2022-04-07T13:50:11Z",
      "side": 1,
      "message": "We\u0027re still working on it, but I think we\u0027re going to be able to resolve it on our end. Setting script_executable seems like the right direction, but we ran into additional problems with some of our docker images, etc... In any case, I expect it to be fully resolved today. Thank you!",
      "parentUuid": "284db568_1c53fb7b",
      "range": {
        "startLine": 26,
        "startChar": 13,
        "endLine": 26,
        "endChar": 27
      },
      "revId": "f57867264a7d661bb904df9f4404521f8e21f022",
      "serverId": "dd02978d-1a8e-36d7-bcc0-a5723e5c0abd"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "e848f09c_1dab4ea7",
        "filename": "generator/dawn_version_generator.py",
        "patchSetId": 10
      },
      "lineNbr": 45,
      "author": {
        "id": 1000002
      },
      "writtenOn": "2022-03-31T08:12:07Z",
      "side": 1,
      "message": "note: since we get the HEAD hash with [1], we don\u0027t technically need to decompress, just validate that packed contains the ref we care about and return it as a dependency? I\u0027m not 100% sure because git might have precedence rules for the decompressed file so nvm, let\u0027s decompress.",
      "revId": "f57867264a7d661bb904df9f4404521f8e21f022",
      "serverId": "dd02978d-1a8e-36d7-bcc0-a5723e5c0abd"
    }
  ]
}